/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.services.UserBookingService;

import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train booking servise");
        Scanner scanner=new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;

        try {
            userBookingService=new UserBookingService();
        } catch (IOException e) {

            //if the users are not loaded, then no actions can be performed.
            System.out.println("Something went wrong");
            return;
        }

        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            Train trainSelectedForBooking = new Train();

            switch (option){
                case 1:

            }
        }

    }
}
